[package]
name = "service_bootloader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
file-db = { version = "0.1", path = "./../file-db" }
serde = { version = "1.0", features = ["derive"] }
linux-info = "0.1.6"
gpt = { version = "2.0", git = "https://github.com/soerenmeier/gpt", branch = "relax_lifetime" }
uuid = "0.8"
# stdio-api = { version = "0.1", path = "./../stdio-api" }
bootloader-api = { package = "service-bootloader-api", version = "0.1", path = "./../service-bootloader-api" }