[workspace]
resolver = "2"

members = [
    "example-binary",
    "file-db",
    "packages-api",
    "packages-publisher",
    "packages-server",
    "service",
    "service-api",
    "service-bootloader",
    "service-bootloader-api",
    "stdio-api",
]

[profile.release]
lto = true
