
SERVICE_BOOLOADER_DIR = $(TOPDIR)/../../service-bootloader

SERVICE_BOOTLOADER_VERSION = 1.0.0
SERVICE_BOOTLOADER_SITE = $(SERVICE_BOOLOADER_DIR)
SERVICE_BOOTLOADER_SITE_METHOD = local

SERVICE_BOOTLOADER_DEPENDENCIES = host-rustc
SERVICE_BOOTLOADER_CARGO_ENV = CARGO_HOME=$(HOST_DIR)/share/cargo \
	__CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS="nightly" \
	CARGO_TARGET_APPLIES_TO_HOST="false"

SERVICE_BOOTLOADER_BIN_DIR = target/$(RUSTC_TARGET_NAME)/release
SERVICE_BOOTLOADER_CARGO_OPTS = \
	-Z target-applies-to-host \
	--target=$(RUSTC_TARGET_NAME) \
	--manifest-path=$(SERVICE_BOOLOADER_DIR)/Cargo.toml \
	--release

define SERVICE_BOOTLOADER_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(SERVICE_BOOTLOADER_CARGO_ENV) \
		cargo build $(SERVICE_BOOTLOADER_CARGO_OPTS)
endef

define SERVICE_BOOTLOADER_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(SERVICE_BOOLOADER_DIR)/$(SERVICE_BOOTLOADER_BIN_DIR)/service_bootloader \
		$(TARGET_DIR)/usr/bin/service-bootloader
endef

$(eval $(generic-package))
