[package]
name = "service"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["time", "macros", "rt-multi-thread", "fs"] }
# stdio-api = { version = "0.1", features = ["async"], path = "./../stdio-api" }
bootloader-api = { package = "service-bootloader-api", version = "0.1", features = ["async"], path = "./../service-bootloader-api" }
fire = { package = "fire-http", version = "0.2", path = "./../../fire-http", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
file-db = { version = "0.1", features = ["async"], path = "./../file-db" }