version: "3.8"
services:
  packages-server:
    image: packages-server
    restart: unless-stopped
    ports:
      - "5426:5426"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/data/packages-server/data:/data"
