services:
  packages-server:
    image: myregistry/iron-os/packages-server
    restart: unless-stopped
    ports:
      - '5426:5426'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './data:/data'
    logging:
      options:
        max-size: '20m'
